table group_trend
	lineageTag: b2371ab9-d05a-512f-b476-66cd9901b7b4

	column 'Coverage Group' =
			SWITCH ( group_trend[analysis_group],
			    "Not expanded by 2023", "Did not expand",
			    "Excluded (early coverage)", "Covered before 2014",
			    "Expanded" )
		dataType: string
		lineageTag: 6a2b98df-6fe7-5410-b7ec-d209b525986e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	measure 'Uninsured Rate' = DIVIDE ( SUM ( group_trend[uninsured] ), SUM ( group_trend[population] ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Trend
		lineageTag: 8734729b-711e-553d-b119-8fa727040aee

	measure 'Expanded in 2014' = CALCULATE ( [Uninsured Rate], group_trend[analysis_group] = "Expanded 2014" )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Trend
		lineageTag: 74db9273-a499-57dd-ac71-8941da891a2e

	measure 'Not expanded' = CALCULATE ( [Uninsured Rate], group_trend[analysis_group] = "Not expanded by 2023" )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Trend
		lineageTag: 405cdaf7-a3e5-5e59-be96-426646656ebe

	measure 'Exp Rate 2023' = CALCULATE ( [Expanded in 2014], group_trend[year] = 2023 )
		formatString: 0%
		displayFolder: Trend
		lineageTag: d4a5d4e0-0869-50e8-9b4e-29a7bcbf3664

	measure 'Exp Rate 2013' = CALCULATE ( [Expanded in 2014], group_trend[year] = 2013 )
		formatString: 0%
		displayFolder: Trend
		lineageTag: ae473993-416c-50c3-b745-1e74c5227475

	measure 'NonExp Rate 2023' = CALCULATE ( [Not expanded], group_trend[year] = 2023 )
		formatString: 0%
		displayFolder: Trend
		lineageTag: 1101828d-2019-5cbc-97b4-7802d585c7f7

	measure 'NonExp Rate 2013' = CALCULATE ( [Not expanded], group_trend[year] = 2013 )
		formatString: 0%
		displayFolder: Trend
		lineageTag: 1fed9824-afbf-562c-993a-68c8f5b21ca2

	measure 'KPI Exp Context' = "down from " & FORMAT ( [Exp Rate 2013], "0%" ) & " in 2013"
		displayFolder: Context
		lineageTag: f36f4dc8-25e4-5d84-96ae-5defe348ab68

	measure 'KPI NonExp Context' = "down from " & FORMAT ( [NonExp Rate 2013], "0%" ) & " in 2013"
		displayFolder: Context
		lineageTag: f4909994-26b6-523e-80c2-5e64b1ed6a3c

	measure 'Uninsured 2023' = CALCULATE ( SUM ( group_trend[uninsured] ), group_trend[year] = 2023 )
		formatString: #,0
		displayFolder: Trend
		lineageTag: f0d87f94-c574-5f67-bca5-2ba3dbc2aefa

	measure 'Waffle Square' = IF ( NOT ISEMPTY ( Waffle ), "■" )
		displayFolder: Waffle
		lineageTag: 95b6a641-590c-5731-b814-454ef1e5ce17

	measure 'Waffle Exp Colour' = IF ( ( 99 - MIN ( Waffle[cell] ) ) < ROUND ( [Exp Rate 2023] * 100, 0 ), "#0E9F6E", "#D5DCD3" )
		displayFolder: Waffle
		lineageTag: 634828f1-4b7f-51c6-a41e-e88b329356fc

	measure 'Waffle NonExp Colour' = IF ( ( 99 - MIN ( Waffle[cell] ) ) < ROUND ( [NonExp Rate 2023] * 100, 0 ), "#D63F6C", "#D5DCD3" )
		displayFolder: Waffle
		lineageTag: f62b3ef2-9cec-5066-925c-88a8f87481a3

	measure 'Exp Uninsured 2013' = [Exp Rate 2013]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: 055bc083-bdca-5e86-90dd-72829a924987

	measure 'Exp Insured 2013' = 1 - [Exp Rate 2013]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: 6c7ca5f8-674e-57a4-bd0a-fc37a590f0b7

	measure 'Exp Uninsured 2023' = [Exp Rate 2023]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: f6a3b0ba-a6fb-547f-b4df-31d82be07b7f

	measure 'Exp Insured 2023' = 1 - [Exp Rate 2023]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: c5f7af9a-a119-5832-aa6c-816a68c63da8

	measure 'NonExp Uninsured 2013' = [NonExp Rate 2013]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: 83d4a4f1-58c8-5046-8d64-ecb4d77c44cd

	measure 'NonExp Insured 2013' = 1 - [NonExp Rate 2013]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: 6be91537-9438-5771-9bda-7721ba9bacaf

	measure 'NonExp Uninsured 2023' = [NonExp Rate 2023]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: b32e678c-598a-50f1-8527-902e93a72e06

	measure 'NonExp Insured 2023' = 1 - [NonExp Rate 2023]
		formatString: 0%
		displayFolder: Donuts
		lineageTag: 411a4a91-4422-54c1-8082-208d901f8359

	measure 'US Uninsured 2023' = CALCULATE ( SUM ( group_trend[uninsured] ), group_trend[year] = 2023 ) / 1000000
		formatString: 0.0"M"
		displayFolder: Overview
		lineageTag: 13a28493-e5d5-58ba-92f1-9a2f30121fd6

	measure 'US Uninsured Context' = "down from " & FORMAT ( CALCULATE ( SUM ( group_trend[uninsured] ), group_trend[year] = 2013 ) / 1000000, "0.0" ) & "M in 2013"
		displayFolder: Overview
		lineageTag: aad67e6d-d8bf-552b-8160-8529a4c26af4

	column analysis_group
		dataType: string
		lineageTag: 35635528-18b2-5947-87db-a347d266510f
		summarizeBy: none
		sourceColumn: analysis_group

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: f04d99a2-4b0e-59d4-b1e4-b860537b696c
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column uninsured
		dataType: int64
		formatString: 0
		lineageTag: 7a795f0a-96d1-59a8-9e71-d6c5d500bf18
		summarizeBy: sum
		sourceColumn: uninsured

		annotation SummarizationSetBy = Automatic

	column population
		dataType: int64
		formatString: 0
		lineageTag: dfba3bfe-d260-55d8-87f3-ca2c37721b0c
		summarizeBy: sum
		sourceColumn: population

		annotation SummarizationSetBy = Automatic

	column pct_uninsured
		dataType: double
		formatString: #,0.00
		lineageTag: 7aa95572-c151-537e-86a9-a1cda2339e1f
		summarizeBy: sum
		sourceColumn: pct_uninsured

		annotation SummarizationSetBy = Automatic

	partition group_trend = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "group_trend.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"analysis_group", type text}, {"year", Int64.Type}, {"uninsured", Int64.Type}, {"population", Int64.Type}, {"pct_uninsured", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
