table model_metrics
	lineageTag: 72d495a6-7b82-5c2e-a684-998d6d0f3a40

	measure 'Effect Years 0-2' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Effect of expansion (years 0-2)" )
		formatString: 0.0" pts"
		displayFolder: Causal
		lineageTag: c7d00b84-9c99-5515-beef-4d7af7c46f5f

	measure 'Effect CI Text' = "95% CI " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_low] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ), "0.0" ) & " to " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_high] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ), "0.0" ) & " points"
		displayFolder: Context
		lineageTag: 8fe7a321-27c8-5f80-9359-9525b11194ab

	measure 'Adults Covered 2023' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Adults covered in 2023 because of expansion" )
		formatString: #,0
		displayFolder: Causal
		lineageTag: c6904e69-ce67-5668-863e-44f7e7746479

	measure 'Covered Context' = "likely between " & FORMAT ( ROUND ( CALCULATE ( SUM ( model_metrics[ci_low] ), model_metrics[metric] = "Adults covered in 2023 because of expansion" ), -4 ), "#,0" ) & " and " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_high] ), model_metrics[metric] = "Adults covered in 2023 because of expansion" ) / 1000000, "0.0" ) & " million"
		displayFolder: Context
		lineageTag: 1ac16739-e9f2-5f42-a626-f3109f433a63

	measure 'Placebo Effect' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Placebo: fake 2011 expansion date" )
		formatString: +0.0" pts";-0.0" pts";0.0" pts"
		displayFolder: Causal
		lineageTag: c90d0217-9331-583d-843c-b6b20da91ac9

	measure 'Placebo Context' = "a fake 2011 date shows no effect, as it should"
		displayFolder: Context
		lineageTag: d969b7f8-fa1a-5e39-bb1e-6639c2c7ea3b

	measure 'Adults Would Gain' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Adults who would gain coverage (10 states)" )
		formatString: #,0
		displayFolder: ML
		lineageTag: 7ce55552-7732-56f8-9a56-23cebcc025f3

	measure 'Gain Context' = "if the 10 remaining states expanded"
		displayFolder: Context
		lineageTag: 2f4c2522-0c03-588a-8e88-8b0823d27f3a

	measure 'Forest Effect' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Causal forest average effect" )
		formatString: 0.0" pts"
		displayFolder: ML
		lineageTag: 912e4af6-2f75-5b62-95e0-e5d0b1e5e356

	measure 'Forest Context' = "difference-in-differences: " & FORMAT ( [Effect Years 0-2], "0.0" ) & " pts"
		displayFolder: Context
		lineageTag: 7c082209-3052-59ab-b750-f2edc9f37b27

	measure 'Effect Plain' = ABS ( CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ) )
		formatString: 0.0" in 100"
		displayFolder: Plain
		lineageTag: 134a1545-401d-5663-9a08-8e022ad229ef

	measure 'Effect Range Text' = "likely between " & FORMAT ( ABS ( CALCULATE ( SUM ( model_metrics[ci_high] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ) ), "0" ) & " and " & FORMAT ( ABS ( CALCULATE ( SUM ( model_metrics[ci_low] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ) ), "0" ) & " in every 100"
		displayFolder: Plain
		lineageTag: 9b9a30c1-91c2-5cd0-99a7-0ddd78627625

	measure 'Checks Passed' = "4 of 4"
		displayFolder: Plain
		lineageTag: dd66929a-fb0c-5a6a-b017-32c01af37afc

	measure 'Checks Context' = "see the checklist below"
		displayFolder: Plain
		lineageTag: be10280d-5d07-5f6a-92fb-ecd15d705e46

	measure 'Rate Change Text' = FORMAT ( CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Uninsured rate today (10 states)" ) / 100, "0%" ) & "  →  " & FORMAT ( CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Uninsured rate if expanded (10 states)" ) / 100, "0%" )
		displayFolder: Plain
		lineageTag: 8db51184-8d66-54e8-9520-c942672bcf94

	measure 'Texas Gain' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Texas adults gaining coverage" )
		formatString: #,0
		displayFolder: Plain
		lineageTag: eabca588-9fef-5d64-afa5-ff3c5b0b0c79

	measure 'Texas Context' = FORMAT ( DIVIDE ( CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Texas adults gaining coverage" ), CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Adults who would gain coverage (10 states)" ) ), "0%" ) & " of the total"
		displayFolder: Plain
		lineageTag: 8e6e8436-e7bc-5c0d-b944-82b4fd4e2c63

	column metric
		dataType: string
		lineageTag: 8968cdc6-ed20-52e0-9970-75d86fdf2359
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 38c63e94-9f8a-57bf-bd7d-d84eabd316b5
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column ci_low
		dataType: double
		formatString: #,0.00
		lineageTag: 97a376e1-8703-5231-ba2e-261a522f7568
		summarizeBy: sum
		sourceColumn: ci_low

		annotation SummarizationSetBy = Automatic

	column ci_high
		dataType: double
		formatString: #,0.00
		lineageTag: 89dc5a1b-3967-5f60-bedc-d992935bc46d
		summarizeBy: sum
		sourceColumn: ci_high

		annotation SummarizationSetBy = Automatic

	partition model_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "model_metrics.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"metric", type text}, {"value", type number}, {"ci_low", type number}, {"ci_high", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
