table model_metrics
	lineageTag: 72d495a6-7b82-5c2e-a684-998d6d0f3a40

	measure 'Effect Years 0-2' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Effect of expansion (years 0-2)" )
		formatString: 0.0" pts"
		displayFolder: Causal
		lineageTag: c7d00b84-9c99-5515-beef-4d7af7c46f5f

	measure 'Effect CI Text' = "95% CI " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_low] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ), "0.0" ) & " to " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_high] ), model_metrics[metric] = "Effect of expansion (years 0-2)" ), "0.0" ) & " points"
		displayFolder: Context
		lineageTag: 8fe7a321-27c8-5f80-9359-9525b11194ab

	measure 'Adults Covered 2023' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Adults covered in 2023 because of expansion" )
		formatString: #,0
		displayFolder: Causal
		lineageTag: c6904e69-ce67-5668-863e-44f7e7746479

	measure 'Covered Context' = "95% CI " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_low] ), model_metrics[metric] = "Adults covered in 2023 because of expansion" ), "#,0" ) & " to " & FORMAT ( CALCULATE ( SUM ( model_metrics[ci_high] ), model_metrics[metric] = "Adults covered in 2023 because of expansion" ), "#,0" )
		displayFolder: Context
		lineageTag: 1ac16739-e9f2-5f42-a626-f3109f433a63

	measure 'Placebo Effect' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Placebo: fake 2011 expansion date" )
		formatString: +0.0" pts";-0.0" pts";0.0" pts"
		displayFolder: Causal
		lineageTag: c90d0217-9331-583d-843c-b6b20da91ac9

	measure 'Placebo Context' = "a fake 2011 date shows no effect, as it should"
		displayFolder: Context
		lineageTag: d969b7f8-fa1a-5e39-bb1e-6639c2c7ea3b

	measure 'Adults Would Gain' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Adults who would gain coverage (10 states)" )
		formatString: #,0
		displayFolder: ML
		lineageTag: 7ce55552-7732-56f8-9a56-23cebcc025f3

	measure 'Gain Context' = "if the 10 remaining states expanded"
		displayFolder: Context
		lineageTag: 2f4c2522-0c03-588a-8e88-8b0823d27f3a

	measure 'Forest Effect' = CALCULATE ( SUM ( model_metrics[value] ), model_metrics[metric] = "Causal forest average effect" )
		formatString: 0.0" pts"
		displayFolder: ML
		lineageTag: 912e4af6-2f75-5b62-95e0-e5d0b1e5e356

	measure 'Forest Context' = "difference-in-differences: " & FORMAT ( [Effect Years 0-2], "0.0" ) & " pts"
		displayFolder: Context
		lineageTag: 7c082209-3052-59ab-b750-f2edc9f37b27

	column metric
		dataType: string
		lineageTag: 8968cdc6-ed20-52e0-9970-75d86fdf2359
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 38c63e94-9f8a-57bf-bd7d-d84eabd316b5
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column ci_low
		dataType: double
		formatString: #,0.00
		lineageTag: 97a376e1-8703-5231-ba2e-261a522f7568
		summarizeBy: sum
		sourceColumn: ci_low

		annotation SummarizationSetBy = Automatic

	column ci_high
		dataType: double
		formatString: #,0.00
		lineageTag: 89dc5a1b-3967-5f60-bedc-d992935bc46d
		summarizeBy: sum
		sourceColumn: ci_high

		annotation SummarizationSetBy = Automatic

	partition model_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "model_metrics.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"metric", type text}, {"value", type number}, {"ci_low", type number}, {"ci_high", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
