table scenario_2023
	lineageTag: 90b88ac0-5303-5aa7-ad82-7bb537fd06a9

	measure 'Scenario Rate' = SUM ( scenario_2023[rate] ) / 100
		formatString: 0%
		displayFolder: Plain
		lineageTag: 24ede6ac-2291-57f3-b719-20f36c231f6d

	measure 'Scenario Colour' = IF ( SELECTEDVALUE ( scenario_2023[order] ) = 1, "#0E9F6E", "#AEB6C0" )
		displayFolder: Plain
		lineageTag: a435e909-1d56-5055-8868-77a816827214

	column scenario
		dataType: string
		sortByColumn: order
		lineageTag: 06e74688-f7da-51f6-b7b2-b6d016900ac2
		summarizeBy: none
		sourceColumn: scenario

		annotation SummarizationSetBy = Automatic

	column rate
		dataType: double
		formatString: #,0.00
		isHidden
		lineageTag: 29f360ad-5190-542e-91d9-477b2e8dcffb
		summarizeBy: sum
		sourceColumn: rate

		annotation SummarizationSetBy = Automatic

	column order
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: eb43a845-4928-529f-a512-4d90847db75b
		summarizeBy: none
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	partition scenario_2023 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "scenario_2023.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"scenario", type text}, {"rate", type number}, {"order", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
