table what_if
	lineageTag: 922a30a5-6489-5ddc-9cab-f1f75d171cba

	measure 'With Expansion' = AVERAGE ( what_if[actual] ) / 100
		formatString: 0%
		displayFolder: Plain
		lineageTag: 707cf1df-e25e-57e3-8640-4b40ce65db7a

	measure 'Without Expansion' = AVERAGE ( what_if[without_expansion] ) / 100
		formatString: 0%
		displayFolder: Plain
		lineageTag: f920a80f-fb69-5bc3-affc-3a7adcd3a665

	column year
		dataType: int64
		formatString: 0
		lineageTag: 09eba1c2-61f0-5d46-a3e9-dba9493a6b40
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column actual
		dataType: double
		formatString: #,0.00
		lineageTag: 8aa42201-304d-557f-bf0d-9413c660da46
		summarizeBy: sum
		sourceColumn: actual

		annotation SummarizationSetBy = Automatic

	column without_expansion
		dataType: double
		formatString: #,0.00
		lineageTag: f4849cf6-6451-5b03-8f04-0141a0e064ac
		summarizeBy: sum
		sourceColumn: without_expansion

		annotation SummarizationSetBy = Automatic

	partition what_if = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "what_if.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year", Int64.Type}, {"actual", type number}, {"without_expansion", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
